[package]
name = "btd-tower-placer"
version = "0.1.0"
authors = ["Benedikt Werner <1benediktwerner@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
